services:
  backend:
    build: .
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
